import {
  UserProfile,
  DonationCampaign,
  DonationTransaction,
  RecurringDonationSubscription,
  AutoGiftConfig,
  MicroBusiness,
  TrainingModule,
  DakwahItem,
  CommunityEvent,
  EncryptedMessage,
  AppNotification,
  CloudBackupSnapshot,
} from './types';

export const initialUserProfile: UserProfile = {
  id: 'usr_grik_001',
  name: 'H. Muhammad Fadhil Kaffah',
  email: 'masjid1.islamicity@gmail.com',
  phone: '+62 812-3456-7890',
  role: 'Pengurus',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  is2FAEnabled: true,
  twoFactorSecret: 'JBSWY3DPEHPK3PXP',
  backupCodes: ['GRIK-9482-1029', 'GRIK-5521-7734', 'GRIK-3312-8841', 'GRIK-6629-4410'],
  publicKeyFingerprint: 'SHA256:7B:9A:F4:1C:88:2E:3D:55:E1:90:3F:8A:2C:4D:AA:09',
  lastLogin: '2026-09-21 21:30:15 WIB',
  biometrics: {
    isEnabled: true,
    biometricType: 'fingerprint',
    protectChat: true,
    protectFinancial: true,
    autoLockMinutes: 5,
    securityPin: '2026',
    isUnlocked: false,
    lastUnlockedTime: undefined,
  },
};

export const initialCampaigns: DonationCampaign[] = [
  {
    id: 'cmp-01',
    title: 'Wakaf Produktif: Sentra Inkubasi & Grosir Halal Umat',
    category: 'Wakaf Produktif',
    description: 'Pembangunan pusat logistik dan distribution center bahan pokok halal langsung dari petani binaan untuk memotong rantai tengkulak dan menekan harga pangan.',
    targetAmount: 500000000,
    collectedAmount: 382500000,
    donorCount: 1420,
    deadline: '2026-11-30',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
    transparencyScore: 99.4,
    milestones: [
      {
        id: 'ms-01-1',
        targetPercent: 25,
        targetAmount: 125000000,
        title: 'Pembebasan Lahan & Sertifikasi Wakaf',
        description: 'Penyelesaian legalitas sertifikat wakaf resmi Badan Wakaf Indonesia (BWI) dan pematangan kavling 2.000m².',
        impactBadge: 'Legalitas Terjamin',
        achieved: true,
        achievedDate: '12 Juli 2026',
      },
      {
        id: 'ms-01-2',
        targetPercent: 50,
        targetAmount: 250000000,
        title: 'Konstruksi Gudang & Struktur Rangka Baja',
        description: 'Pembangunan fisik warehouse logistik modern dengan akses loading dock truk distributor pangan.',
        impactBadge: 'Fisik 100% Berdiri',
        achieved: true,
        achievedDate: '28 Agustus 2026',
      },
      {
        id: 'ms-01-3',
        targetPercent: 75,
        targetAmount: 375000000,
        title: 'Instalasi Cold Storage & Rak Logistik Halal',
        description: 'Pengadaan pendingin komersial 50 ton untuk produk segar dan sistem inventaris digital terintegrasi.',
        impactBadge: 'Kapasitas 50 Ton Siap',
        achieved: true,
        achievedDate: '20 September 2026',
      },
      {
        id: 'ms-01-4',
        targetPercent: 100,
        targetAmount: 500000000,
        title: 'Operasional Penuh & Rantai Pasok 50 Warung Umat',
        description: 'Penyaluran pasokan perdana ke 50 warung kelontong mitra binaan tanpa perantara tengkulak.',
        impactBadge: 'Pemberdayaan 50 Warung',
        achieved: false,
      },
    ],
    disbursements: [
      {
        id: 'disb-101',
        date: '2026-09-15',
        recipient: 'Kontraktor Amanah Perkasa',
        amount: 85000000,
        purpose: 'Tahap 1: Pondasi dan struktur baja warehouse sentra halal',
        proofDocument: 'INVOICE-WF-001.pdf',
        auditStatus: 'Terverifikasi',
      },
      {
        id: 'disb-102',
        date: '2026-09-18',
        recipient: 'Kelompok Tani Berkah Al-Ikhlas',
        amount: 45000000,
        purpose: 'Pengadaan bibit unggul & pupuk organik konsorsium',
        proofDocument: 'KWITANSI-AGRO-09.pdf',
        auditStatus: 'Terverifikasi',
      },
    ],
  },
  {
    id: 'cmp-02',
    title: 'Dana Bergulir Qardhul Hasan: Modal Usaha 100 Ibu Tangguh',
    category: 'Modal UMKM',
    description: 'Bantuan modal pinjaman kebajikan tanpa bunga dan tanpa jaminan bagi ibu rumah tangga prasejahtera perintis usaha kuliner halal dan kerajinan.',
    targetAmount: 200000000,
    collectedAmount: 168400000,
    donorCount: 915,
    deadline: '2026-10-31',
    imageUrl: 'https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=600&q=80',
    transparencyScore: 100,
    milestones: [
      {
        id: 'ms-02-1',
        targetPercent: 25,
        targetAmount: 50000000,
        title: 'Penyaluran Modal Klaster 1: 25 Ibu Pengrajin',
        description: 'Pencairan modal kerja produktif perdana @Rp 2.000.000 dengan akad Qardh murni tanpa margin sepeserpun.',
        impactBadge: '25 UMKM Aktif',
        achieved: true,
        achievedDate: '15 Juli 2026',
      },
      {
        id: 'ms-02-2',
        targetPercent: 50,
        targetAmount: 100000000,
        title: 'Penyaluran Modal Klaster 2: 25 Ibu Kuliner Halal',
        description: 'Bantuan modal pengadaan bahan baku dan sertifikasi Halal Self-Declare gratis untuk 25 mitra kuliner.',
        impactBadge: 'Sertifikasi Halal Tuntas',
        achieved: true,
        achievedDate: '10 Agustus 2026',
      },
      {
        id: 'ms-02-3',
        targetPercent: 75,
        targetAmount: 150000000,
        title: 'Penyaluran Modal Klaster 3: 25 Ibu Toko Kelontong',
        description: 'Pengadaan display toko dan integrasi mesin POS pembukuan kasir digital GRIK Pay mikro.',
        impactBadge: 'Kasir Digital GRIK Aktif',
        achieved: true,
        achievedDate: '12 September 2026',
      },
      {
        id: 'ms-02-4',
        targetPercent: 100,
        targetAmount: 200000000,
        title: 'Penyaluran Modal Klaster 4: 25 Ibu Tangguh Klaster 4',
        description: 'Penuntasan target 100 keluarga mandiri dan pembentukan Koperasi Simpan Pinjam Syariah Komunitas.',
        impactBadge: 'Genap 100 Ibu Tangguh',
        achieved: false,
      },
    ],
    disbursements: [
      {
        id: 'disb-201',
        date: '2026-09-10',
        recipient: '35 Pelaku Usaha Mikro Binaan Klaster 1',
        amount: 70000000,
        purpose: 'Penyaluran modal kerja mikro @Rp 2.000.000 skema Qardh murni',
        proofDocument: 'BAST-QARDH-K1.pdf',
        auditStatus: 'Terverifikasi',
      },
    ],
  },
  {
    id: 'cmp-03',
    title: 'Zakat Mal Pengentasan Kemiskinan Berbasis Pendidikan Vokasi',
    category: 'Zakat',
    description: 'Penyaluran Zakat Mal tepat sasaran 8 asnaf untuk beasiswa vokasi teknologi dan bisnis syariah bagi pemuda duafa hingga mandiri.',
    targetAmount: 150000000,
    collectedAmount: 135200000,
    donorCount: 740,
    deadline: '2026-12-15',
    imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=600&q=80',
    transparencyScore: 98.8,
    milestones: [
      {
        id: 'ms-03-1',
        targetPercent: 25,
        targetAmount: 37500000,
        title: 'Seleksi Asnaf & Asrama 20 Santri Duafa',
        description: 'Verifikasi kelayakan asnaf fakir-miskin dan penyediaan asrama tinggal dengan fasilitas belajar layak.',
        impactBadge: '20 Santri Terpilih',
        achieved: true,
        achievedDate: '01 Agustus 2026',
      },
      {
        id: 'ms-03-2',
        targetPercent: 50,
        targetAmount: 75000000,
        title: 'Pengadaan 20 Laptop & Fasilitas Laboratorium Coding',
        description: 'Perangkat komputasi kerja modern untuk pelatihan rekayasa web frontend, mobile, dan data.',
        impactBadge: 'Lab Komputer Lengkap',
        achieved: true,
        achievedDate: '22 Agustus 2026',
      },
      {
        id: 'ms-03-3',
        targetPercent: 75,
        targetAmount: 112500000,
        title: 'Bootcamp 300 Jam & Sertifikasi Industri Syariah',
        description: 'Kurikulum intensif bersama praktisi industri, etika bisnis Islam, dan penguasaan bahasa asing.',
        impactBadge: 'Lulus Uji Kompetensi',
        achieved: true,
        achievedDate: '15 September 2026',
      },
      {
        id: 'ms-03-4',
        targetPercent: 100,
        targetAmount: 150000000,
        title: 'Penempatan Kerja Mandiri & Inkubasi Usaha Rintisan',
        description: 'Penyaluran ke jaringan perusahaan mitra syariah dan modal pendirian agency teknologi mandiri santri.',
        impactBadge: '100% Siap Kerja Mandiri',
        achieved: false,
      },
    ],
    disbursements: [
      {
        id: 'disb-301',
        date: '2026-09-05',
        recipient: 'Lembaga Vokasi Coding & Desain Kaffah',
        amount: 42000000,
        purpose: 'Biaya asrama & sertifikasi profesi 20 santri vokasi',
        proofDocument: 'SPP-VOKASI-BCH3.pdf',
        auditStatus: 'Terverifikasi',
      },
    ],
  },
];

export const initialTransactions: DonationTransaction[] = [
  {
    id: 'TRX-GRIK-20260921-001',
    campaignId: 'cmp-02',
    campaignTitle: 'Dana Bergulir Qardhul Hasan: Modal Usaha 100 Ibu Tangguh',
    donorName: 'Ahmad Sholihin',
    amount: 1500000,
    type: 'Modal Mikro',
    timestamp: '2026-09-21 20:45:12',
    isAnonymous: false,
    paymentMethod: 'BSI',
    status: 'Berhasil',
    e2eeReceiptHash: '0x8f2c3b4a919e8271a7d65c4321fedcba',
  },
  {
    id: 'TRX-GRIK-20260921-002',
    campaignId: 'cmp-01',
    campaignTitle: 'Wakaf Produktif: Sentra Inkubasi & Grosir Halal Umat',
    donorName: 'Hamba Allah',
    amount: 5000000,
    type: 'Wakaf Produktif',
    timestamp: '2026-09-21 19:12:00',
    isAnonymous: true,
    paymentMethod: 'QRIS',
    status: 'Berhasil',
    e2eeReceiptHash: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
  },
  {
    id: 'TRX-GRIK-20260921-003',
    campaignId: 'cmp-03',
    campaignTitle: 'Zakat Mal Pengentasan Kemiskinan Berbasis Pendidikan Vokasi',
    donorName: 'dr. Siti Rahmawati',
    amount: 3250000,
    type: 'Zakat Mal',
    timestamp: '2026-09-21 17:33:41',
    isAnonymous: false,
    paymentMethod: 'Bank Syariah',
    status: 'Berhasil',
    e2eeReceiptHash: '0x99887766554433221100aabbccddeeff',
  },
  {
    id: 'TRX-GRIK-20260920-004',
    campaignId: 'cmp-02',
    campaignTitle: 'Dana Bergulir Qardhul Hasan: Modal Usaha 100 Ibu Tangguh',
    donorName: 'Fauzan Hakim',
    amount: 500000,
    type: 'Sedekah Subuh',
    timestamp: '2026-09-20 05:15:22',
    isAnonymous: false,
    paymentMethod: 'GRIK Pay',
    status: 'Berhasil',
    e2eeReceiptHash: '0xaa11bb22cc33dd44ee55ff6600778899',
  },
];

export const initialRecurringSubscriptions: RecurringDonationSubscription[] = [
  {
    id: 'sub-01',
    campaignId: 'cmp-01',
    campaignTitle: 'Wakaf Produktif: Sentra Inkubasi & Grosir Halal Umat',
    category: 'Wakaf Produktif',
    monthlyAmount: 250000,
    frequency: 'Bulanan',
    billingDay: 5,
    nextBillingDate: '05 Oktober 2026',
    paymentMethod: 'Auto-Debit BSI',
    status: 'Aktif',
    startDate: '05 Mei 2026',
    totalDonatedSoFar: 1250000,
    autoDeduct: true,
  },
  {
    id: 'sub-02',
    campaignId: 'cmp-02',
    campaignTitle: 'Dana Bergulir Qardhul Hasan: Modal Usaha 100 Ibu Tangguh',
    category: 'Modal UMKM',
    monthlyAmount: 150000,
    frequency: 'Bulanan',
    billingDay: 12,
    nextBillingDate: '12 Oktober 2026',
    paymentMethod: 'GRIK Pay Kas Syariah',
    status: 'Aktif',
    startDate: '12 Juni 2026',
    totalDonatedSoFar: 600000,
    autoDeduct: true,
  },
  {
    id: 'sub-03',
    campaignId: 'cmp-03',
    campaignTitle: 'Zakat Mal Pengentasan Kemiskinan Berbasis Pendidikan Vokasi',
    category: 'Zakat',
    monthlyAmount: 375000,
    frequency: 'Bulanan',
    billingDay: 25,
    nextBillingDate: '25 Oktober 2026',
    paymentMethod: 'Bank Syariah Muamalat',
    status: 'Aktif',
    startDate: '25 April 2026',
    totalDonatedSoFar: 1875000,
    autoDeduct: true,
    isAutoZakat: true,
    designatedInstitution: 'BAZNAS (Badan Amil Zakat Nasional)',
    autoZakatDetails: {
      monthlyIncome: 18000000,
      additionalIncome: 2000000,
      monthlyExpenses: 5000000,
      savingsAndCash: 80000000,
      goldAndInvestments: 25000000,
      receivables: 0,
      goldPricePerGram: 1420000,
      nisabMonthly: 10058333,
      isNisabReached: true,
      totalAssets: 105000000,
      netMonthlyIncome: 15000000,
      zakatableBaseMonthly: 15000000,
      calculatedZakatMonthly: 375000,
      designatedInstitution: 'BAZNAS (Badan Amil Zakat Nasional)',
      autoDebitDay: 25,
    },
  },
];

export const initialAutoGiftConfig: AutoGiftConfig = {
  id: 'autogift-cfg-01',
  isEnabled: true,
  totalMonthlyBudget: 1000000,
  billingDay: 25,
  paymentMethod: 'Auto-Debit BSI',
  allocations: [
    {
      category: 'Zakat',
      percentage: 40,
      designatedCampaignId: 'cmp-03',
      notes: 'Zakat Mal Pengentasan Kemiskinan Berbasis Vokasi',
    },
    {
      category: 'Wakaf Produktif',
      percentage: 30,
      designatedCampaignId: 'cmp-01',
      notes: 'Sentra Inkubasi & Grosir Halal Umat',
    },
    {
      category: 'Modal UMKM',
      percentage: 20,
      designatedCampaignId: 'cmp-02',
      notes: 'Dana Bergulir Qardhul Hasan Modal 100 Ibu Tangguh',
    },
    {
      category: 'Infaq',
      percentage: 10,
      designatedCampaignId: 'cmp-03',
      notes: 'Infaq Dakwah & Beasiswa Santri Quran',
    },
  ],
  lastDisbursedDate: '25 Agustus 2026',
  nextExecutionDate: '25 Oktober 2026',
  totalDisbursedLifetime: 4000000,
  historyLogs: [
    {
      id: 'ag-log-20260825',
      date: '25 Agustus 2026',
      totalAmount: 1000000,
      status: 'Berhasil',
      receiptHash: '0x8899aabbccddeeff0011223344556677',
      allocations: [
        { category: 'Zakat', campaignTitle: 'Zakat Mal Pengentasan Kemiskinan Berbasis Vokasi', amount: 400000, percentage: 40 },
        { category: 'Wakaf Produktif', campaignTitle: 'Wakaf Sentra Grosir Halal Umat', amount: 300000, percentage: 30 },
        { category: 'Modal UMKM', campaignTitle: 'Modal 100 Ibu Tangguh Qardhul Hasan', amount: 200000, percentage: 20 },
        { category: 'Infaq', campaignTitle: 'Infaq Dakwah Santri Quran', amount: 100000, percentage: 10 },
      ],
    },
    {
      id: 'ag-log-20260725',
      date: '25 Juli 2026',
      totalAmount: 1000000,
      status: 'Berhasil',
      receiptHash: '0x7766554433221100ffeeddccbbaa9988',
      allocations: [
        { category: 'Zakat', campaignTitle: 'Zakat Mal Pengentasan Kemiskinan Berbasis Vokasi', amount: 400000, percentage: 40 },
        { category: 'Wakaf Produktif', campaignTitle: 'Wakaf Sentra Grosir Halal Umat', amount: 300000, percentage: 30 },
        { category: 'Modal UMKM', campaignTitle: 'Modal 100 Ibu Tangguh Qardhul Hasan', amount: 200000, percentage: 20 },
        { category: 'Infaq', campaignTitle: 'Infaq Dakwah Santri Quran', amount: 100000, percentage: 10 },
      ],
    },
  ],
};

export const initialMicroBusinesses: MicroBusiness[] = [
  {
    id: 'biz-01',
    name: 'Dapur Berkah Bunda Halal Food',
    ownerName: 'Ibu Nurbaiti',
    sector: 'Kuliner Halal',
    description: 'Produksi aneka lauk frozen siap saji higienis berbahan rempah lokal, bersertifikat halal BPJPH, tanpa pengawet sintesis.',
    location: 'Bandung Timur, Jawa Barat',
    employees: 4,
    monthlyTurnover: 28500000,
    fundingNeeded: 15000000,
    fundingRaised: 15000000,
    halalCertified: true,
    status: 'Mandiri',
    qardhEligible: true,
    rating: 4.9,
    contact: '0812-9988-7711',
  },
  {
    id: 'biz-02',
    name: 'Hijab Syari Al-Kautsar Eco-Weave',
    ownerName: 'Fatimah Az-Zahra',
    sector: 'Busana Muslim',
    description: 'Konveksi gamis dan khimar syari syariah-compliant menggunakan kain serat bambu ramah lingkungan dan pewarna herbal.',
    location: 'Solo, Jawa Tengah',
    employees: 6,
    monthlyTurnover: 42000000,
    fundingNeeded: 25000000,
    fundingRaised: 18500000,
    halalCertified: true,
    status: 'Inkubasi',
    qardhEligible: true,
    rating: 4.8,
    contact: '0813-4455-6677',
  },
  {
    id: 'biz-03',
    name: 'Berkah Tani Organik Kaffah',
    ownerName: 'Kang Ujang Supriatna',
    sector: 'Agrobisnis',
    description: 'Pertanian beras merah organik dan sayur hidroponik bebas pestisida kimia dengan sistem bagi hasil adil kemitraan jamaah masjid.',
    location: 'Cianjur, Jawa Barat',
    employees: 8,
    monthlyTurnover: 55000000,
    fundingNeeded: 35000000,
    fundingRaised: 30000000,
    halalCertified: true,
    status: 'Ekspansi',
    qardhEligible: true,
    rating: 5.0,
    contact: '0815-1122-3344',
  },
  {
    id: 'biz-04',
    name: 'Madinah Herbal & Thibbun Nabawi',
    ownerName: 'Ust. Ridwan Arifin',
    sector: 'Kuliner Halal',
    description: 'Madu murni multiflora hutan riau, minyak zaitun perasan pertama, habbatussauda teruji laboratorium terakreditasi.',
    location: 'Surabaya, Jawa Timur',
    employees: 3,
    monthlyTurnover: 22000000,
    fundingNeeded: 12000000,
    fundingRaised: 12000000,
    halalCertified: true,
    status: 'Mandiri',
    qardhEligible: true,
    rating: 4.9,
    contact: '0817-8899-0011',
  },
];

export const initialTrainingModules: TrainingModule[] = [
  {
    id: 'mod-01',
    title: 'Fiqih Muamalah Kontemporer untuk Pelaku UMKM',
    level: 'Dasar',
    durationMinutes: 120,
    category: 'Fiqih Muamalah',
    description: 'Memahami rukun dan syarat jual beli sah, larangan riba, gharar (ketidakjelasan), maysir (judi), serta akad kerja sama syariah Mudharabah & Musyarakah.',
    lessonsCount: 6,
    completedLessons: 6,
    instructor: 'Dr. KH. Abdullah Gymnastiar, M.E.Sy',
    badge: 'Khatam Fiqih Muamalah',
    quiz: [
      {
        question: 'Apakah hukum menambahkan denda keterlambatan uang pokok pinjaman dalam akad pinjaman tunai?',
        options: [
          'Boleh jika disepakati sejak awal',
          'Riba nasi’ah yang diharamkan syariat',
          'Halal sebagai biaya administrasi bank',
          'Boleh atas kerelaan peminjam',
        ],
        correctIndex: 1,
        explanation: 'Setiap pinjaman yang mendatangkan manfaat lebih (kelebihan pokok) merupakan riba yang dilarang tegas berdasarkan ijma ulama.',
      },
      {
        question: 'Dalam akad Mudharabah, siapakah yang menanggung kerugian finansial murni bukan karena kelalaian pengelola?',
        options: [
          'Pengelola usaha (Mudharib)',
          'Pemilik modal (Shahibul Mal)',
          'Ditanggung berdua sama rata',
          'Pemerintah atau lembaga penjamin',
        ],
        correctIndex: 1,
        explanation: 'Dalam Mudharabah, kerugian finansial ditanggung pemilik modal, sedangkan pengelola merugi waktu dan tenaga, kecuali terbukti ada wanprestasi.',
      },
    ],
  },
  {
    id: 'mod-02',
    title: 'Manajemen Arus Kas & Pemisahan Dompet Usaha Mikro',
    level: 'Dasar',
    durationMinutes: 90,
    category: 'Manajemen Keuangan',
    description: 'Praktek praktis mencatat penerimaan, pengeluaran, margin laba kotor vs bersih, dan disiplin tidak mencampurkan uang dapur dan uang usaha.',
    lessonsCount: 5,
    completedLessons: 4,
    instructor: 'Hj. Dewi Sartika, SE., Ak., CA',
    badge: 'Kas Berkah Kaffah',
    quiz: [
      {
        question: 'Mengapa rekening pribadi dan usaha mikro harus dipisahkan sejak hari pertama berjualan?',
        options: [
          'Agar terhindar dari pajak pemerintah',
          'Untuk mengetahui secara akurat laba riil usaha dan mencegah modal terpakai konsumsi pribadi',
          'Hanya formalitas untuk pinjaman bank',
          'Agar terlihat keren di mata pembeli',
        ],
        correctIndex: 1,
        explanation: 'Pemisahan rekening mencegah erosi modal usaha dan memungkinkan evaluasi kelayakan usaha secara objektif.',
      },
    ],
  },
  {
    id: 'mod-03',
    title: 'Akselerasi Pemasaran Digital Beretika & Halal Branding',
    level: 'Menengah',
    durationMinutes: 150,
    category: 'Digital Marketing',
    description: 'Teknik copywriting tanpa manipulasi (shiddiq), optimasi marketplace, fotografi produk smartphone, dan membangun loyalitas pelanggan berbasis nilai berkah.',
    lessonsCount: 8,
    completedLessons: 5,
    instructor: 'Rizki Pratama, M.Sc (Digital Growth)',
    badge: 'Marketer Amanah',
    quiz: [
      {
        question: 'Bagaimana etika deskripsi produk syariah yang benar dalam platform e-commerce?',
        options: [
          'Menyembunyikan sedikit cacat agar cepat laku',
          'Menjelaskan kondisi riil secara jujur termasuk spesifikasi dan garansi',
          'Menggunakan testimoni palsu agar dipercaya',
          'Menulis promo yang berlebihan',
        ],
        correctIndex: 1,
        explanation: 'Rasulullah SAW bersabda: "Penjual dan pembeli memiliki hak khiyar selama belum berpisah. Jika keduanya jujur dan menjelaskan, keduanya diberkahi".',
      },
    ],
  },
  {
    id: 'mod-04',
    title: 'Panduan Praktis Sertifikasi Halal Gratis (Self-Declare)',
    level: 'Menengah',
    durationMinutes: 80,
    category: 'Sertifikasi Halal',
    description: 'Tata cara pendaftaran sertifikat halal SiHalal BPJPH, verifikasi bahan baku daftar positif, dan penyiapan Manual Sistem Jaminan Produk Halal (SJPH).',
    lessonsCount: 4,
    completedLessons: 3,
    instructor: 'Ir. Ahmad Zarkasi (Auditor Halal)',
    badge: 'Siap Halal BPJPH',
    quiz: [
      {
        question: 'Bahan apa yang wajib memiliki sertifikat halal atau berasal dari daftar positif dalam produk makanan olahan?',
        options: [
          'Semua bahan tambahan pangan seperti gelatin, flavor, pengemulsi, dan daging sembelihan',
          'Hanya air mineral saja',
          'Hanya kemasan plastik',
          'Tidak ada yang wajib',
        ],
        correctIndex: 0,
        explanation: 'Bahan hewani dan turunan kimiawi berisiko tinggi wajib memiliki traceability halal yang jelas.',
      },
    ],
  },
];

export const initialDakwahItems: DakwahItem[] = [
  {
    id: 'dkw-01',
    title: 'LIVE: Membangun Kemandirian Ekonomi Umat Berfondasi Tauhid',
    speaker: 'KH. Bachtiar Nasir, Lc., M.M & Tim Pakar GRIK',
    category: 'Live Streaming',
    date: '2026-09-21',
    time: '20:00 WIB',
    duration: '90 Menit',
    isLive: true,
    liveViewers: 1842,
    videoUrl: 'https://www.youtube.com/embed/live_stream_demo',
    summary: 'Bedah tuntas strategi integrasi masjid sebagai sentra ekonomi syariah dan pemberdayaan pedagang kecil keliling menjadi pengusaha mandiri.',
  },
  {
    id: 'dkw-02',
    title: 'Fiqih Akad Jual Beli: Menghindari Riba Tersembunyi di Era FinTech',
    speaker: 'Ustadz Dr. Erwandi Tarmizi, M.A',
    category: 'Fiqih Bisnis',
    date: '2026-09-20',
    time: '09:00 WIB',
    duration: '65 Menit',
    isLive: false,
    audioUrl: 'https://example.com/audio/fiqih-fintech.mp3',
    summary: 'Kajian mendalam tentang paylater, cashback bersyarat, dropshipping syar’i, dan skema murabahah yang tepat menurut fatwa DSN-MUI.',
  },
  {
    id: 'dkw-03',
    title: 'Keluarga Sakinah: Mengelola Keuangan Rumah Tangga yang Penuh Barakah',
    speaker: 'Ustadz Bendri Jaisyurrahman',
    category: 'Keluarga Sakinah',
    date: '2026-09-18',
    time: '16:00 WIB',
    duration: '52 Menit',
    isLive: false,
    videoUrl: 'https://example.com/video/keluarga-sakinah.mp4',
    summary: 'Pilar keterbukaan nafkah antara suami istri, sedekah rahasia penolak bala, dan mendidik anak memiliki jiwa entrepreneur Qurani.',
  },
  {
    id: 'dkw-04',
    title: 'Tafsir Tematik Al-Baqarah 275-281: Kehancuran Riba & Keberkahan Sedekah',
    speaker: 'Ustadz Adi Hidayat, Lc., M.A',
    category: 'Tafsir Tematik',
    date: '2026-09-15',
    time: '05:30 WIB',
    duration: '48 Menit',
    isLive: false,
    audioUrl: 'https://example.com/audio/tafsir-riba.mp3',
    summary: 'Mengapa Allah memusnahkan riba dan menyuburkan sedekah. Konsekuensi logis bagi peradaban yang meninggalkan sistem riba.',
  },
];

export const initialEvents: CommunityEvent[] = [
  {
    id: 'evt-01',
    title: 'Kajian Akbar Kaffah & Santunan 500 Yatim & Duafa',
    category: 'Dakwah',
    date: '2026-09-27',
    time: '08:30 - 12:00 WIB',
    location: 'Masjid Raya Islamic Center & Live Zoom Global',
    isOnline: false,
    attendeesCount: 650,
    speakerOrLead: 'Dewan Syariah GRIK & Ulama Tamu',
    reminderSet: true,
  },
  {
    id: 'evt-02',
    title: 'Bootcamp Intensif UMKM: 3 Hari Siap Ekspor Halal',
    category: 'Pelatihan Bisnis',
    date: '2026-10-03',
    time: '09:00 - 16:30 WIB',
    location: 'Sentra Inkubasi GRIK & Hybrid Online',
    isOnline: true,
    attendeesCount: 180,
    speakerOrLead: 'Konsultan Ekspor Kemenag & Praktisi Dagang',
    reminderSet: true,
  },
  {
    id: 'evt-03',
    title: 'Pasar Rakyat Muamalah Syariah & Bazar Beras Murah',
    category: 'Sosial/Baksos',
    date: '2026-10-10',
    time: '07:00 - 14:00 WIB',
    location: 'Plaza Komunitas GRIK Selatan',
    isOnline: false,
    attendeesCount: 1200,
    speakerOrLead: 'Divisi Pemberdayaan Ekonomi Umat',
    reminderSet: false,
  },
  {
    id: 'evt-04',
    title: 'Rapat Pleno Dewan Pengurus: Laporan Akuntabilitas Kuartal III',
    category: 'Rapat Komunitas',
    date: '2026-09-30',
    time: '19:30 - 21:30 WIB',
    location: 'Ruang Virtual Aman E2EE GRIK',
    isOnline: true,
    attendeesCount: 45,
    speakerOrLead: 'Sekretariat Jenderal GRIK',
    reminderSet: true,
  },
];

export const initialMessages: EncryptedMessage[] = [
  {
    id: 'msg-01',
    senderId: 'usr_grik_002',
    senderName: 'Ustadz Dr. Hamzah Al-Farisi (Dewan Syariah)',
    senderRole: 'Dewan Syariah',
    recipientId: 'usr_grik_001',
    recipientName: 'H. Muhammad Fadhil Kaffah',
    content: 'Assalamu’alaikum Warahmatullah Akhi Fadhil. Verifikasi penyaluran Qardhul Hasan klaster kuliner minggu ini telah diaudit dan sesuai syariat 100%.',
    ciphertext: 'U2FsdGVkX19z4N8v1Q7W8aK9pLm2Xy3Z4a5b6c7d8e9f0a1b2c3d4e5f6g7h8i9j',
    iv: 'a1b2c3d4e5f60718',
    timestamp: '2026-09-21 21:10:04',
    isEncrypted: true,
    fingerprint: 'E2EE-SHA256:7B9AF41C882E',
  },
  {
    id: 'msg-02',
    senderId: 'usr_grik_001',
    senderName: 'H. Muhammad Fadhil Kaffah',
    senderRole: 'Pengurus',
    recipientId: 'usr_grik_002',
    recipientName: 'Ustadz Dr. Hamzah Al-Farisi (Dewan Syariah)',
    content: 'Wa’alaikumsalam Ustadz. Alhamdulillah, tanda terima digital dan bukti transfer telah diunggah ke buku kas transparan publik.',
    ciphertext: 'U2FsdGVkX1+vG7w9qZ1x3L5n7P9r1T3v5X7z9B1d3F5h7J9l1N3p5R7t9V1x3Z',
    iv: '9f8e7d6c5b4a3928',
    timestamp: '2026-09-21 21:12:30',
    isEncrypted: true,
    fingerprint: 'E2EE-SHA256:7B9AF41C882E',
  },
  {
    id: 'msg-03',
    senderId: 'usr_grik_003',
    senderName: 'Ibu Nurbaiti (Dapur Berkah Bunda)',
    senderRole: 'Pelaku UMKM',
    recipientId: 'usr_grik_001',
    recipientName: 'H. Muhammad Fadhil Kaffah',
    content: 'Jazakallahu khairan Pak Pengurus GRIK. Bantuan modal bergulir Qardh tanpa bunga sudah kami belikan mesin vakum sealer. Penjualan kami naik 40%!',
    ciphertext: 'U2FsdGVkX1/bC3dE5fG7hI9jK1lM3nO5pQ7rS9tU1vW3xY5zA7bC9dE1fG3hI',
    iv: '4b3c2d1e0f9a8b7c',
    timestamp: '2026-09-21 21:18:55',
    isEncrypted: true,
    fingerprint: 'E2EE-SHA256:7B9AF41C882E',
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif-01',
    title: 'Kajian Siaran Langsung Sedang Berlangsung',
    message: 'KH. Bachtiar Nasir membawakan tema Kemandirian Ekonomi Umat. Bergabung sekarang bersama 1.800+ jamaah!',
    type: 'dakwah',
    timestamp: '5 menit yang lalu',
    isRead: false,
    actionTab: 'dakwah',
  },
  {
    id: 'notif-02',
    title: 'Donasi Masuk Terverifikasi',
    message: 'Donasi sebesar Rp 1.500.000 untuk Qardhul Hasan berhasil dicatat ke Ledger Transparan publik.',
    type: 'donasi',
    timestamp: '45 menit yang lalu',
    isRead: false,
    actionTab: 'donasi',
  },
  {
    id: 'notif-03',
    title: 'Sertifikasi Halal Berhasil Disetujui',
    message: 'UMKM binaan Berkah Tani Organik telah memperoleh sertifikat resmi SiHalal BPJPH!',
    type: 'bisnis',
    timestamp: '2 jam yang lalu',
    isRead: true,
    actionTab: 'ekonomi',
  },
  {
    id: 'notif-04',
    title: 'Sinkronisasi Otomatis Cloud Berhasil',
    message: 'Semua snapshot data transaksi dan kemajuan pelatihan telah diamankan ke Cloud GRIK terenkripsi.',
    type: 'sistem',
    timestamp: '1 jam yang lalu',
    isRead: true,
    actionTab: 'backup_ekspor',
  },
];

export const initialSnapshots: CloudBackupSnapshot[] = [
  {
    id: 'snap-20260921-2100',
    timestamp: '2026-09-21 21:00:00 WIB',
    sizeBytes: 428900,
    version: 'v2.4.0-kaffah-prod',
    deviceInfo: 'GRIK Cloud Server (asia-east1) - Automated Cron',
    recordCounts: {
      donations: 4,
      businesses: 4,
      events: 4,
      messages: 3,
    },
  },
  {
    id: 'snap-20260921-1200',
    timestamp: '2026-09-21 12:00:00 WIB',
    sizeBytes: 412600,
    version: 'v2.4.0-kaffah-prod',
    deviceInfo: 'GRIK Cloud Server (asia-east1) - Automated Cron',
    recordCounts: {
      donations: 3,
      businesses: 4,
      events: 4,
      messages: 2,
    },
  },
  {
    id: 'snap-20260920-2359',
    timestamp: '2026-09-20 23:59:59 WIB',
    sizeBytes: 398200,
    version: 'v2.3.9-kaffah-prod',
    deviceInfo: 'Daily Golden Snapshot - Offsite Vault Encrypted',
    recordCounts: {
      donations: 3,
      businesses: 3,
      events: 3,
      messages: 2,
    },
  },
];

export const initialUser = initialUserProfile;
export const initialBusinesses = initialMicroBusinesses;
